// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package tam_project_server

type Chatroom struct {
	Name    string     `json:"name"`
	Message []*Message `json:"message"`
}

type Message struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
