// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package tam_project_server

type Chatroom struct {
	Name    string     `json:"name"`
	Message []*Message `json:"message"`
	ID      string     `json:"id"`
}

type Message struct {
	Text string `json:"text"`
	ID   string `json:"id"`
}
